alias cdn='nnn'
alias pip='pip3'
alias python='python3'
alias py='python3'
alias kvim='kitty nvim'
alias x='xdg-open'
alias pup='sudo pacman -Syu'
alias wifistat='iwctl station wlan0 show'
alias wifidc='iwctl station wlan0 disconnect'
alias wifilist='iwctl station wlan0 get-networks'
alias wifiscan='iwctl station wlan0 scan'
alias wifi='iwctl station wlan0'
alias wificon='iwctl station wlan0 connect'
alias pinstall='sudo pacman -S'
alias psearch='pacman -Ss'
alias puninstall='sudo pacman --remove'
alias reconky='killall -SIGUSR1 conky'
alias sstart='sudo systemctl start'
alias sstop='sudo systemctl stop'
alias sstatus='systemctl status'
alias senable='sudo systemctl enable'
alias sdisable='sudo systemctl disable'
alias copy='xclip -sel clip'
alias shortprompt='export PS1="$ "'
alias px='__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia'